version: "3.1"
services:
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "TRUE"
    ports:
      - "3306:3306"
  app:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    links:
      - db
